In [1]:
import numpy as np

In [3]:
# Criação de uma matriz com 100 elementos. Do 0 ao 99
arr = np.arange(100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [5]:
# Criação de uma lista com 100 elementos também
lista = list(range(100))
lista

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [8]:
# Exibe o tempo de processamento/carregamento de um array (multiplicando-o por 2),
# sendo ele mais rápido em comparação à lista
%time for _ in range(10): arr2 = arr * 2

CPU times: user 77 µs, sys: 9 µs, total: 86 µs
Wall time: 91.6 µs


In [9]:
# Exibe o tempo de processamento/carregamento de uma lista
%time for _ in range(10): lista2 = [x * 2 for x in lista]

CPU times: user 133 µs, sys: 0 ns, total: 133 µs
Wall time: 138 µs


In [10]:
# Imprime o array multiplicado por 2
arr2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198])

## NDarrays

In [11]:
# Criação de um array aleatório com 2 linhas e 3 colunas
data = np.random.randn(2,3)
data

array([[ 0.51989409,  1.27857385,  0.46037068],
       [-0.25891715,  1.01708101, -0.67920119]])

In [12]:
data * 10

array([[ 5.19894088, 12.78573854,  4.60370679],
       [-2.58917147, 10.17081011, -6.79201186]])

In [13]:
# Soma entre a matriz 1 e a matriz 2
data + data

array([[ 1.03978818,  2.55714771,  0.92074136],
       [-0.51783429,  2.03416202, -1.35840237]])

In [14]:
data1 = np.random.randn(2,2)
data1

array([[ 0.31353695, -0.60823982],
       [-0.25753976, -1.00350592]])

In [15]:
# Gera um erro porque as matrizes têm dimensões distintas
data + data1

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [18]:
data + 5

array([[5.51989409, 6.27857385, 5.46037068],
       [4.74108285, 6.01708101, 4.32079881]])

In [19]:
data

array([[ 0.51989409,  1.27857385,  0.46037068],
       [-0.25891715,  1.01708101, -0.67920119]])

In [21]:
# Para se descobrir as dimensões
data.shape

(2, 3)

In [22]:
# Retorna com o elemento com base na posição
data[0][1]

1.2785738544878515

In [23]:
# Cria uma lista e exibe na tela
data1 = [6, 7.5, 2, 3,4]
data1

[6, 7.5, 2, 3, 4]

In [24]:
# Converte a lista criada em um array
arr1 = np.array(data1)
arr1

array([6. , 7.5, 2. , 3. , 4. ])

In [26]:
print('O tipo de objeto de data1 é:', type(data1))
print('O tipo de objeto de arr1 é:', type(arr1))

O tipo de objeto de data1 é: <class 'list'>
O tipo de objeto de arr1 é: <class 'numpy.ndarray'>


In [27]:
# Cria uma nova lista
data2 = [[1,2,3,4], [5,6,7,8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [28]:
# Converte a lista criada em um array
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
arr3 = np.array([[1,2,3,4], [5,6,7,'7']])
arr3

array([['1', '2', '3', '4'],
       ['5', '6', '7', '7']], dtype='<U21')

Tipos de dados: https://numpy.org/doc/stable/reference/arrays.dtypes.html

In [30]:
# Tipo unicode string
arr3.dtype

dtype('<U21')

In [31]:
# Tipo inteiro de 64 bits
arr2.dtype

dtype('int64')

In [35]:
# Criação de um array de strings
num_string = np.array(['1.25', '4.6', '5.2', '7.8'])
num_string

array(['1.25', '4.6', '5.2', '7.8'], dtype='<U4')

In [36]:
num_string.dtype

dtype('<U4')

In [38]:
# Transforma o array de string em número decimais
num_float = num_string.astype(float)
num_float

array([1.25, 4.6 , 5.2 , 7.8 ])

In [39]:
num_float.dtype

dtype('float64')

In [40]:
np.array('1.25')

array('1.25', dtype='<U4')

In [41]:
type('ola')

str

In [42]:
num_string.dtype == np.array('1.25').dtype

True

In [43]:
type('1.25')

str

In [44]:
type(0.22)

float

In [46]:
int_array = np.arange(10)
arr1 = np.array([.22, .270, .357, .330, .44, .50], dtype = np.float64)
arr1

array([0.22 , 0.27 , 0.357, 0.33 , 0.44 , 0.5  ])

In [47]:
type(arr1[0])

numpy.float64

In [48]:
type(float(arr1[0]))

float

## Aritmética com arrays

In [49]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [51]:
arr1 = np.array([[1., 2.], [4., 5.]])
arr1

array([[1., 2.],
       [4., 5.]])

In [52]:
# Multiplicação entre arrays iguais
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [53]:
# Gera um erro porque as dimensões são distintas
arr * arr1

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [54]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [55]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [57]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [58]:
arr ** 5

array([[1.000e+00, 3.200e+01, 2.430e+02],
       [1.024e+03, 3.125e+03, 7.776e+03]])

In [59]:
(arr ** 5) ** (1/3)

array([[ 1.        ,  3.1748021 ,  6.24025147],
       [10.0793684 , 14.62008869, 19.81156349]])